FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    gcc \
    python3.7-dev && \
    apt-get clean

WORKDIR /app
COPY . .

RUN pip install -r requirements-api.txt

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
