services:
  postgres:
    image: postgres:14
    container_name: postgres
    env_file: 
      - .env  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: service
    env_file: 
      - .env  
    depends_on:
      - postgres
    network_mode: host

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    env_file: 
      - .env  
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    
volumes:
  postgres_data:
